name = "Jspec"
uuid = "799228a4-d83e-4675-bef0-fa04f023a533"
authors = ["Stefano Covino <stefano.covino@inaf.it> and contributors"]
version = "1.2.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CairoMakie = "0.11, 0.12, 0.15"
DataFrames = "1"
FITSIO = "0.17"
LaTeXStrings = "1"
julia = "1.9, 1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
